### PR TITLE
[WIP] add support for FitNesse config file,use xml formatted output

### PR DESCRIPTION
**Pull request by aneesh-joseph**
setting up an early PR to get feedback for
- [x] Added support for supplying an optional FitNesse config file.
- [x] Change Fitnesse output format to xml so that the maven plugin works well with the Jenkins Fitnesse plugin
- [x] speed up the test execution - store the fitnesse XML report as is, Do not create HTML reports in the test runner mojo(just dump the result xml files) and produce a simple result with test failure, exception counts etc - use VTD to parse
- [ ] Update the report mojo to generate HTML reports using the XML files generated by the test runner mojo - use VTD to parse
- [ ] Now that the PR will fix compatibility issues with the Jenkins Fitnesse plugin(just publish `**/fitnesse-results.xml`), should the plugin really try to generate a surefire report?. The Jenkins Fitnesse plugin is capable of adjusting the Build result to STABLE, UNSTABLE etc based on the test results
- [ ] Support latest fitnesse version - may be just a matter of updating the docs?
  :smile:

### CODE REVIEW

**Comment by aneesh-joseph** [comment]
@sijpesteijn - can you have a look at the proposed changes please :smile:

**Comment by sijpesteijn** [comment]
Hi Joseph, 

I would love to, but currently I'm enjoying my holidays and I did not bring my laptop. I will take a look when I get back. (2 weeks)

Cheers Gijs

**Comment by aneesh-joseph** [comment]
enjoy your holidays :smile:

Cheers
Aneesh

**Comment by The-Alchemist** [comment]
@sijpesteijn : Thoughts on merging? :)

**Comment by sijpesteijn** [comment]
I merged your code and I will try to make a release. Sorry, I've been preoccupied with other stuff. I don't longer use Fitnesse. You are welcome to continue the development. Just let me know and I'll hand it over to you :)

**Comment by sijpesteijn** [comment]
Hi Aneesh,

Version 2.1.12 has been released. Let me know if it's working for you.
cheers, Gijs

http://search.maven.org/#artifactdetails%7Cnl.sijpesteijn.testing.fitnesse.plugins%7Cmafia-maven-plugin%7C2.1.12%7Cmaven-plugin

**Pull request merged**
